# Generated by Django 5.0.6 on 2024-06-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_subscription_old_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('subscription', 'Subscription'), ('payg', 'Pay-as-you-go')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
