# Generated by Django 5.0.6 on 2024-06-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_subscription_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='remaining_quotes',
            field=models.IntegerField(default=0),
        ),
    ]
