# Generated by Django 5.0.6 on 2024-06-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ojm_core', '0002_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='request',
            name='readiness',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
