# Generated by Django 5.0.6 on 2024-06-19 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ojm_core', '0003_alter_notification_options_alter_request_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_type', models.CharField(choices=[('Negotiable', 'Negotiable'), ('Fixed Price', 'Fixed Price'), ('Starting Fee', 'Starting Fee'), ('Per hour', 'Per hour')], max_length=50)),
                ('price_details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('electrician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ojm_core.request')),
            ],
        ),
    ]
