# Generated by Django 5.0.6 on 2024-06-29 11:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ojm_core', '0005_servicecategory_servicesubcategory_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='ServiceRequest',
        ),
    ]
