# Generated by Django 5.0.6 on 2024-06-01 19:57

import django.db.models.deletion
import userauth.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.CreateModel(
            name='ElectricianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('service_description', models.TextField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=userauth.models.user_directory_path)),
                ('founded_date', models.DateField()),
                ('registered', models.BooleanField(default=False)),
                ('country', models.CharField(choices=[('nigeria', 'Nigeria'), ('benin', 'Benin'), ('burkina-faso', 'Burkina Faso'), ('cape-verde', 'Cape Verde'), ('cote-divoire', "Côte d'Ivoire (Ivory Coast)"), ('gambia', 'Gambia'), ('ghana', 'Ghana'), ('guinea', 'Guinea'), ('guinea-bissau', 'Guinea-Bissau'), ('liberia', 'Liberia'), ('mali', 'Mali'), ('mauritania', 'Mauritania'), ('niger', 'Niger'), ('senegal', 'Senegal'), ('sierra-leone', 'Sierra Leone'), ('togo', 'Togo')], max_length=50)),
                ('state', models.CharField(choices=[('abia', 'Abia'), ('adamawa', 'Adamawa'), ('akwa-ibom', 'Akwa Ibom'), ('anambra', 'Anambra'), ('bauchi', 'Bauchi'), ('bayelsa', 'Bayelsa'), ('benue', 'Benue'), ('borno', 'Borno'), ('cross-river', 'Cross River'), ('delta', 'Delta'), ('ebonyi', 'Ebonyi'), ('edo', 'Edo'), ('ekiti', 'Ekiti'), ('enugu', 'Enugu'), ('gombe', 'Gombe'), ('imo', 'Imo'), ('jigawa', 'Jigawa'), ('kaduna', 'Kaduna'), ('kano', 'Kano'), ('katsina', 'Katsina'), ('kebbi', 'Kebbi'), ('kogi', 'Kogi'), ('kwara', 'Kwara'), ('lagos', 'Lagos'), ('nasarawa', 'Nasarawa'), ('niger', 'Niger'), ('ogun', 'Ogun'), ('ondo', 'Ondo'), ('osun', 'Osun'), ('oyo', 'Oyo'), ('plateau', 'Plateau'), ('rivers', 'Rivers'), ('sokoto', 'Sokoto'), ('taraba', 'Taraba'), ('yobe', 'Yobe'), ('zamfara', 'Zamfara'), ('fct', 'Federal Capital Territory (FCT)')], max_length=50)),
                ('city', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('terms', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
