# Generated by Django 5.0.6 on 2024-06-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_customerprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerprofile',
            options={'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='electricianprofile',
            options={'verbose_name_plural': 'Electricians'},
        ),
        migrations.AddField(
            model_name='electricianprofile',
            name='number_of_employees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='electricianprofile',
            name='prices',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electricianprofile',
            name='qualification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electricianprofile',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electricianprofile',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
