# Generated by Django 5.0.6 on 2024-06-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_alter_customerprofile_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricianprofile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
