# Generated by Django 5.0.6 on 2024-06-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_electricianprofile_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricianprofile',
            name='cac',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
