# Generated by Django 5.0.6 on 2024-06-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0007_electricianprofile_cac'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electricianprofile',
            old_name='verified',
            new_name='cac_verified',
        ),
        migrations.AddField(
            model_name='electricianprofile',
            name='id_verified',
            field=models.BooleanField(default=False),
        ),
    ]
