# Generated by Django 5.0.6 on 2024-06-19 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0008_rename_verified_electricianprofile_cac_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(choices=[('National Identity Card', 'National Identity Card'), ("Driver's License", "Driver's License"), ("Voter's Card", "Voter's Card"), ('International Passport', 'International Passport')], max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('id_front_page', models.ImageField(upload_to='id_front_pages/')),
                ('id_back_page', models.ImageField(blank=True, null=True, upload_to='id_back_pages/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
